### ISSUE TITLE
Synchronous Exception

### ISSUE THREAD

**Issue by btauro** [rsta2/circle64#2]
Hi,
I have been trying to initialize the MMU by calling initCMemorySystem (int bEnableMMU)
I have been getting the following exception
```
Synchronous exception: Data abort, same EL, Address size fault at level 1:
ESR_EL1 00000025og96000061 ELR_EL1 00000000000003C4
 SPSR_EL1 0000000000083C18 FAR_EL1 0000000000083C20
 X30 000000000029FF60
 SpEl0 00000000002A8000
 Sp_EL1 000000000029FF94

```
Could you guide me on what could be the reason

**Comment by rsta2** [comment]
The MMU is normally enabled by default, because CMemorySystem is instantiated in CKernel for all sample programs. You do not need do call the constructor manually and must not do it, because this tries to initialise the MMU twice.

With which Circle64 sample does this problem occur? I would need the *kernel8.lst* file to be able to map the addresses to the code. But this exception message looks strange to me. This is not a Circle64 output.

**Comment by btauro** [comment]
where is  CMemorySystem  in CKernel i could not find them in the sample code
this parameter when set in Transalation Table 3   `pDesc->Ignored       = 0;`
gives me the exception if i remove it runs without the exception.
yes this is not circle 64 output as i am just printing the registers on exception for now
but on circle 64 when i try running this on Gpio for example it does not work.

**Comment by rsta2** [comment]
CMemorySystem is a member object of CKernel. See the file [kernel.h](https://github.com/rsta2/circle64/blob/master/sample/01-gpiosimple/kernel.h#L46) for the declaration. When *CKernel* is instantiated in main() in the file [main.cpp](https://github.com/rsta2/circle64/blob/master/sample/01-gpiosimple/main.cpp#L27) the constructor of all member objects of CKernel is called automatically. This is not visible in *kernel.cpp*. There is also not a member initialiser required, because the constructor of *CMemorySystem* has a default parameter *TRUE* for *bEnableMMU*. Look [here](https://github.com/rsta2/circle64/blob/master/include/circle/memory.h#L30) for the declaration. In the end this means that the *sample/01-gpiosimple* runs with the MMU activated without modification.

Unfortunately I cannot reproduce your problem with *sample/01-gpiosimple* here. It runs successfully, also if build with GCC 7.2.1. I cannot confirm the problem with `pDesc->Ignored = 0;`.

**Comment by btauro** [comment]
Thank you for your help will look into this.
